name: Auto-Preprocess Data on Raw Data Change # Nama workflow di GitHub Actions

on:
  push:
    branches:
      - master # Ganti dengan nama branch utama Anda (misal: 'master')
    paths:
      - 'personality_raw/**' # Trigger workflow jika ada perubahan di folder data mentah Anda

jobs:
  preprocess_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Sesuaikan dengan versi Python Anda

    - name: Install Python Dependencies # Langkah ketiga: Menginstal library Python yang dibutuhkan
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Ubah baris ini untuk menginstal dari requirements.txt

    - name: Run Data Preprocessing Script
      run: |
        # Panggil script preprocessing Anda dari root repository MLOPS/
        python preprocessing/automate_Nama-siswa.py

    - name: Configure Git for Commit
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Commit and Push Processed Data
      run: |
        # Pastikan path ini menunjuk ke file hasil preprocessing Anda
        git add preprocessing/personality_preprocessing/processed_data.csv
        git commit -m "chore: Update processed data via GitHub Actions" || echo "No changes to commit"
        git push origin master # Ganti jika branch utama Anda bukan 'main' (misal: 'master')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token otomatis dari GitHub Actions

    - name: Upload Processed Data as Artifact (Optional but Recommended)
      uses: actions/upload-artifact@v4
      with:
        name: processed-data-artifact
        path: preprocessing/personality_preprocessing/processed_data.csv
        retention-days: 5